local registryLib = require("me2.item.registry")
local identityLib = require("me2.item.identity")
local fakeHasher = require("spec.support.fake_hasher")

describe("identity", function()
  it("returns the hash and caches the descriptor", function()
    local hasher = fakeHasher.new()
    hasher:set({ side = 2, slot = 1 }, "HASH_IRON",
      { name = "iron", label = "Iron Ingot", damage = 0, size = 3 })
    local registry = registryLib.new()
    local id = identityLib.new(hasher, registry)

    local key = id:identifyAt({ side = 2, slot = 1 })
    assert.are.equal("HASH_IRON", key)
    assert.is_true(registry:has("HASH_IRON"))
    assert.are.equal("Iron Ingot", registry:get("HASH_IRON").label)
  end)

  it("returns nil plus an error for an empty location", function()
    local id = identityLib.new(fakeHasher.new(), registryLib.new())
    local key, err = id:identifyAt({ side = 2, slot = 9 })
    assert.is_nil(key)
    assert.is_string(err)
  end)

  it("gives the same key for the same item regardless of stack size", function()
    local hasher = fakeHasher.new()
    hasher:set({ side = 2, slot = 1 }, "H", { name = "iron", label = "Iron", size = 1 })
    hasher:set({ side = 2, slot = 2 }, "H", { name = "iron", label = "Iron", size = 64 })
    local registry = registryLib.new()
    local id = identityLib.new(hasher, registry)
    assert.are.equal("H", id:identifyAt({ side = 2, slot = 1 }))
    assert.are.equal("H", id:identifyAt({ side = 2, slot = 2 }))
    assert.are.equal(1, registry:count())
  end)

  it("fails loud when one hash maps to conflicting descriptors", function()
    local hasher = fakeHasher.new()
    hasher:set({ side = 2, slot = 1 }, "H", { name = "iron", size = 1 })
    hasher:set({ side = 2, slot = 2 }, "H", { name = "gold", size = 1 })
    local id = identityLib.new(hasher, registryLib.new())
    id:identifyAt({ side = 2, slot = 1 })
    assert.has_error(function() id:identifyAt({ side = 2, slot = 2 }) end)
  end)
end)
